# Generated by Django 4.1.7 on 2023-02-16 04:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=255, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.SlugField(max_length=255, unique=True)),
                ('main_image', models.SlugField(max_length=255, unique=True)),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
